//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 08:43:40 AM CDT 
//


package com.deanhealthplan.memberinfo.domain.api.memberinforesp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Result">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}Header" minOccurs="0"/>
 *                   &lt;element name="Member" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="contractID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="memberID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="personID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="memberLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="memberFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="memberMiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="memberTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="memberSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="memberDateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="memberSexCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="memberClassCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="memberNetworkID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="benefitPackageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="benefitPackageID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="multipleBenefitPackageFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="recordStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="remarksIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="coverageContractHolderFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="voidFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="typeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="lineOfBusiness" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="businessLevel4ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="businessLevel5ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="businessLevel6ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="businessLevel7ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="employerGroupLevelID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="crossReferenceFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="providerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="effectiveDateMPNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="endDateMPNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="providerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="zipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{}Error" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "result"
})
@XmlRootElement(name = "MemberGetMTVMemberInfoResp")
public class MemberGetMTVMemberInfoResp {

    @XmlElement(name = "Result", required = true)
    protected MemberGetMTVMemberInfoResp.Result result;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link MemberGetMTVMemberInfoResp.Result }
     *     
     */
    public MemberGetMTVMemberInfoResp.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberGetMTVMemberInfoResp.Result }
     *     
     */
    public void setResult(MemberGetMTVMemberInfoResp.Result value) {
        this.result = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}Header" minOccurs="0"/>
     *         &lt;element name="Member" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="contractID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="memberID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="personID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="memberLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="memberFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="memberMiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="memberTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="memberSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="memberDateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="memberSexCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="memberClassCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="memberNetworkID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="benefitPackageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="benefitPackageID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="multipleBenefitPackageFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="recordStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="remarksIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="coverageContractHolderFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="voidFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="typeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="lineOfBusiness" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="businessLevel4ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="businessLevel5ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="businessLevel6ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="businessLevel7ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="employerGroupLevelID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="crossReferenceFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="providerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="effectiveDateMPNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="endDateMPNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="providerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="zipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{}Error" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "header",
        "member",
        "error"
    })
    public static class Result {

        @XmlElement(name = "Header")
        protected Header header;
        @XmlElement(name = "Member")
        protected List<MemberGetMTVMemberInfoResp.Result.Member> member;
        @XmlElement(name = "Error")
        protected List<Error> error;

        /**
         * Gets the value of the header property.
         * 
         * @return
         *     possible object is
         *     {@link Header }
         *     
         */
        public Header getHeader() {
            return header;
        }

        /**
         * Sets the value of the header property.
         * 
         * @param value
         *     allowed object is
         *     {@link Header }
         *     
         */
        public void setHeader(Header value) {
            this.header = value;
        }

        /**
         * Gets the value of the member property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the member property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMember().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MemberGetMTVMemberInfoResp.Result.Member }
         * 
         * 
         */
        public List<MemberGetMTVMemberInfoResp.Result.Member> getMember() {
            if (member == null) {
                member = new ArrayList<MemberGetMTVMemberInfoResp.Result.Member>();
            }
            return this.member;
        }

        /**
         * Gets the value of the error property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the error property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getError().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Error }
         * 
         * 
         */
        public List<Error> getError() {
            if (error == null) {
                error = new ArrayList<Error>();
            }
            return this.error;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="contractID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="memberID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="personID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="memberLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="memberFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="memberMiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="memberTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="memberSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="memberDateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="memberSexCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="memberClassCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="memberNetworkID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="benefitPackageType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="benefitPackageID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="multipleBenefitPackageFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="recordStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="remarksIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="coverageContractHolderFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="voidFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="typeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="lineOfBusiness" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="businessLevel4ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="businessLevel5ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="businessLevel6ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="businessLevel7ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="employerGroupLevelID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="crossReferenceFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="statusCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="providerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="effectiveDateMPNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="endDateMPNA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="providerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="zipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "contractID",
            "memberID",
            "personID",
            "memberLastName",
            "memberFirstName",
            "memberMiddleName",
            "memberTitle",
            "memberSuffix",
            "memberDateOfBirth",
            "memberSexCode",
            "memberClassCode",
            "memberNetworkID",
            "benefitPackageType",
            "benefitPackageID",
            "multipleBenefitPackageFlag",
            "recordStatus",
            "remarksIndicator",
            "coverageContractHolderFlag",
            "voidFlag",
            "effectiveDate",
            "endDate",
            "typeCode",
            "lineOfBusiness",
            "businessLevel4ID",
            "businessLevel5ID",
            "businessLevel6ID",
            "businessLevel7ID",
            "employerGroupLevelID",
            "crossReferenceFlag",
            "statusCode",
            "providerID",
            "effectiveDateMPNA",
            "endDateMPNA",
            "providerName",
            "zipCode",
            "count"
        })
        public static class Member {

            protected String contractID;
            protected String memberID;
            protected String personID;
            protected String memberLastName;
            protected String memberFirstName;
            protected String memberMiddleName;
            protected String memberTitle;
            protected String memberSuffix;
            protected String memberDateOfBirth;
            protected String memberSexCode;
            protected String memberClassCode;
            protected String memberNetworkID;
            protected String benefitPackageType;
            protected String benefitPackageID;
            protected String multipleBenefitPackageFlag;
            protected String recordStatus;
            protected String remarksIndicator;
            protected String coverageContractHolderFlag;
            protected String voidFlag;
            protected String effectiveDate;
            protected String endDate;
            protected String typeCode;
            protected String lineOfBusiness;
            protected String businessLevel4ID;
            protected String businessLevel5ID;
            protected String businessLevel6ID;
            protected String businessLevel7ID;
            protected String employerGroupLevelID;
            protected String crossReferenceFlag;
            protected String statusCode;
            protected String providerID;
            protected String effectiveDateMPNA;
            protected String endDateMPNA;
            protected String providerName;
            protected String zipCode;
            protected String count;

            /**
             * Gets the value of the contractID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContractID() {
                return contractID;
            }

            /**
             * Sets the value of the contractID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContractID(String value) {
                this.contractID = value;
            }

            /**
             * Gets the value of the memberID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMemberID() {
                return memberID;
            }

            /**
             * Sets the value of the memberID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMemberID(String value) {
                this.memberID = value;
            }

            /**
             * Gets the value of the personID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPersonID() {
                return personID;
            }

            /**
             * Sets the value of the personID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPersonID(String value) {
                this.personID = value;
            }

            /**
             * Gets the value of the memberLastName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMemberLastName() {
                return memberLastName;
            }

            /**
             * Sets the value of the memberLastName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMemberLastName(String value) {
                this.memberLastName = value;
            }

            /**
             * Gets the value of the memberFirstName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMemberFirstName() {
                return memberFirstName;
            }

            /**
             * Sets the value of the memberFirstName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMemberFirstName(String value) {
                this.memberFirstName = value;
            }

            /**
             * Gets the value of the memberMiddleName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMemberMiddleName() {
                return memberMiddleName;
            }

            /**
             * Sets the value of the memberMiddleName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMemberMiddleName(String value) {
                this.memberMiddleName = value;
            }

            /**
             * Gets the value of the memberTitle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMemberTitle() {
                return memberTitle;
            }

            /**
             * Sets the value of the memberTitle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMemberTitle(String value) {
                this.memberTitle = value;
            }

            /**
             * Gets the value of the memberSuffix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMemberSuffix() {
                return memberSuffix;
            }

            /**
             * Sets the value of the memberSuffix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMemberSuffix(String value) {
                this.memberSuffix = value;
            }

            /**
             * Gets the value of the memberDateOfBirth property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMemberDateOfBirth() {
                return memberDateOfBirth;
            }

            /**
             * Sets the value of the memberDateOfBirth property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMemberDateOfBirth(String value) {
                this.memberDateOfBirth = value;
            }

            /**
             * Gets the value of the memberSexCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMemberSexCode() {
                return memberSexCode;
            }

            /**
             * Sets the value of the memberSexCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMemberSexCode(String value) {
                this.memberSexCode = value;
            }

            /**
             * Gets the value of the memberClassCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMemberClassCode() {
                return memberClassCode;
            }

            /**
             * Sets the value of the memberClassCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMemberClassCode(String value) {
                this.memberClassCode = value;
            }

            /**
             * Gets the value of the memberNetworkID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMemberNetworkID() {
                return memberNetworkID;
            }

            /**
             * Sets the value of the memberNetworkID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMemberNetworkID(String value) {
                this.memberNetworkID = value;
            }

            /**
             * Gets the value of the benefitPackageType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBenefitPackageType() {
                return benefitPackageType;
            }

            /**
             * Sets the value of the benefitPackageType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBenefitPackageType(String value) {
                this.benefitPackageType = value;
            }

            /**
             * Gets the value of the benefitPackageID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBenefitPackageID() {
                return benefitPackageID;
            }

            /**
             * Sets the value of the benefitPackageID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBenefitPackageID(String value) {
                this.benefitPackageID = value;
            }

            /**
             * Gets the value of the multipleBenefitPackageFlag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMultipleBenefitPackageFlag() {
                return multipleBenefitPackageFlag;
            }

            /**
             * Sets the value of the multipleBenefitPackageFlag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMultipleBenefitPackageFlag(String value) {
                this.multipleBenefitPackageFlag = value;
            }

            /**
             * Gets the value of the recordStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRecordStatus() {
                return recordStatus;
            }

            /**
             * Sets the value of the recordStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRecordStatus(String value) {
                this.recordStatus = value;
            }

            /**
             * Gets the value of the remarksIndicator property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRemarksIndicator() {
                return remarksIndicator;
            }

            /**
             * Sets the value of the remarksIndicator property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRemarksIndicator(String value) {
                this.remarksIndicator = value;
            }

            /**
             * Gets the value of the coverageContractHolderFlag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCoverageContractHolderFlag() {
                return coverageContractHolderFlag;
            }

            /**
             * Sets the value of the coverageContractHolderFlag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCoverageContractHolderFlag(String value) {
                this.coverageContractHolderFlag = value;
            }

            /**
             * Gets the value of the voidFlag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVoidFlag() {
                return voidFlag;
            }

            /**
             * Sets the value of the voidFlag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVoidFlag(String value) {
                this.voidFlag = value;
            }

            /**
             * Gets the value of the effectiveDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEffectiveDate() {
                return effectiveDate;
            }

            /**
             * Sets the value of the effectiveDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEffectiveDate(String value) {
                this.effectiveDate = value;
            }

            /**
             * Gets the value of the endDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndDate() {
                return endDate;
            }

            /**
             * Sets the value of the endDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndDate(String value) {
                this.endDate = value;
            }

            /**
             * Gets the value of the typeCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTypeCode() {
                return typeCode;
            }

            /**
             * Sets the value of the typeCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTypeCode(String value) {
                this.typeCode = value;
            }

            /**
             * Gets the value of the lineOfBusiness property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLineOfBusiness() {
                return lineOfBusiness;
            }

            /**
             * Sets the value of the lineOfBusiness property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLineOfBusiness(String value) {
                this.lineOfBusiness = value;
            }

            /**
             * Gets the value of the businessLevel4ID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBusinessLevel4ID() {
                return businessLevel4ID;
            }

            /**
             * Sets the value of the businessLevel4ID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBusinessLevel4ID(String value) {
                this.businessLevel4ID = value;
            }

            /**
             * Gets the value of the businessLevel5ID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBusinessLevel5ID() {
                return businessLevel5ID;
            }

            /**
             * Sets the value of the businessLevel5ID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBusinessLevel5ID(String value) {
                this.businessLevel5ID = value;
            }

            /**
             * Gets the value of the businessLevel6ID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBusinessLevel6ID() {
                return businessLevel6ID;
            }

            /**
             * Sets the value of the businessLevel6ID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBusinessLevel6ID(String value) {
                this.businessLevel6ID = value;
            }

            /**
             * Gets the value of the businessLevel7ID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBusinessLevel7ID() {
                return businessLevel7ID;
            }

            /**
             * Sets the value of the businessLevel7ID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBusinessLevel7ID(String value) {
                this.businessLevel7ID = value;
            }

            /**
             * Gets the value of the employerGroupLevelID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmployerGroupLevelID() {
                return employerGroupLevelID;
            }

            /**
             * Sets the value of the employerGroupLevelID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmployerGroupLevelID(String value) {
                this.employerGroupLevelID = value;
            }

            /**
             * Gets the value of the crossReferenceFlag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCrossReferenceFlag() {
                return crossReferenceFlag;
            }

            /**
             * Sets the value of the crossReferenceFlag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCrossReferenceFlag(String value) {
                this.crossReferenceFlag = value;
            }

            /**
             * Gets the value of the statusCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatusCode() {
                return statusCode;
            }

            /**
             * Sets the value of the statusCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatusCode(String value) {
                this.statusCode = value;
            }

            /**
             * Gets the value of the providerID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProviderID() {
                return providerID;
            }

            /**
             * Sets the value of the providerID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProviderID(String value) {
                this.providerID = value;
            }

            /**
             * Gets the value of the effectiveDateMPNA property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEffectiveDateMPNA() {
                return effectiveDateMPNA;
            }

            /**
             * Sets the value of the effectiveDateMPNA property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEffectiveDateMPNA(String value) {
                this.effectiveDateMPNA = value;
            }

            /**
             * Gets the value of the endDateMPNA property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEndDateMPNA() {
                return endDateMPNA;
            }

            /**
             * Sets the value of the endDateMPNA property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEndDateMPNA(String value) {
                this.endDateMPNA = value;
            }

            /**
             * Gets the value of the providerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProviderName() {
                return providerName;
            }

            /**
             * Sets the value of the providerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProviderName(String value) {
                this.providerName = value;
            }

            /**
             * Gets the value of the zipCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZipCode() {
                return zipCode;
            }

            /**
             * Sets the value of the zipCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZipCode(String value) {
                this.zipCode = value;
            }

            /**
             * Gets the value of the count property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCount() {
                return count;
            }

            /**
             * Sets the value of the count property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCount(String value) {
                this.count = value;
            }

        }

    }

}
