//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.06 at 08:43:40 AM CDT 
//


package com.deanhealthplan.memberinfo.domain.api.memberinforesp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.deanhealthplan.memberinfo.domain.api.memberinforesp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReturnCode_QNAME = new QName("", "returnCode");
    private final static QName _ContextString_QNAME = new QName("", "contextString");
    private final static QName _ErrorCode_QNAME = new QName("", "errorCode");
    private final static QName _CorrelationID_QNAME = new QName("", "correlationID");
    private final static QName _SeverityCode_QNAME = new QName("", "severityCode");
    private final static QName _ReasonCode_QNAME = new QName("", "reasonCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.deanhealthplan.memberinfo.domain.api.memberinforesp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MemberGetMTVMemberInfoResp }
     * 
     */
    public MemberGetMTVMemberInfoResp createMemberGetMTVMemberInfoResp() {
        return new MemberGetMTVMemberInfoResp();
    }

    /**
     * Create an instance of {@link MemberGetMTVMemberInfoResp.Result }
     * 
     */
    public MemberGetMTVMemberInfoResp.Result createMemberGetMTVMemberInfoRespResult() {
        return new MemberGetMTVMemberInfoResp.Result();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link MemberGetMTVMemberInfoResp.Result.Member }
     * 
     */
    public MemberGetMTVMemberInfoResp.Result.Member createMemberGetMTVMemberInfoRespResultMember() {
        return new MemberGetMTVMemberInfoResp.Result.Member();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "returnCode")
    public JAXBElement<String> createReturnCode(String value) {
        return new JAXBElement<String>(_ReturnCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contextString")
    public JAXBElement<String> createContextString(String value) {
        return new JAXBElement<String>(_ContextString_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "errorCode")
    public JAXBElement<String> createErrorCode(String value) {
        return new JAXBElement<String>(_ErrorCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "correlationID")
    public JAXBElement<String> createCorrelationID(String value) {
        return new JAXBElement<String>(_CorrelationID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "severityCode")
    public JAXBElement<String> createSeverityCode(String value) {
        return new JAXBElement<String>(_SeverityCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reasonCode")
    public JAXBElement<String> createReasonCode(String value) {
        return new JAXBElement<String>(_ReasonCode_QNAME, String.class, null, value);
    }

}
