apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: member-info-service
  labels:
    app: member-info-service
spec:
  selector:
    matchLabels:
      app: member-info-service
  template:
    metadata:
      labels:
        app: member-info-service
    spec:
      containers:
      - name: member-info-service
        image: dhpcontainreg.azurecr.io/core-mtv/memberinfoservice:v3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: mtvmemberinfo
        securityContext:
          runAsUser: 1000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: member-info-service
  labels:
    app: member-info-service
    registerWithMesh: "true"
    appLanguage: "java"
    framework: "spring_boot"
    frameworkVersion: "2.0.5"
spec:
  type: NodePort
  ports:
  - name: member-info-service
    port: 8080
    targetPort: "mtvmemberinfo"
  selector:
    app: member-info-service

