# **********************************************************************************************************************************
# THESE ARE THE MEMBER INFO BASE CONFIGURATIONS.  
# **********************************************************************************************************************************
spring:
  application:
    name: MemberInfoService
server:
  port: 9102
  servlet:
    contextPath: /mtvmembersearch/
# **********************************************************************************************************************************
# Zipkin related stuff
# spring.sleuth.sampler.probability=1   for slueth
# **********************************************************************************************************************************
spring.zipkin.baseUrl: http://default-servicemesh-zipkin-http/
spring.sleuth.sampler.percentage: 1.0 
# **********************************************************************************************************************************
# THIS IS FOR THE /actuator/info ENDPOINT.  ADD ANY INFORMATION HERE TO BE PRESENTED.
# **********************************************************************************************************************************  
info:
  app:
    name: Member Info MicroService
    description: process Calling MTV API
endpoints:
  health:
    sensitive: false
    show-details: always
management:
  info:
    git:
      mode: FULL
