# **********************************************************************************************************************************
# THESE ARE THE MEMBER INFO BASE CONFIGURATIONS.  
# **********************************************************************************************************************************
spring:
  application:
    name: MemberInfoService
#server:
#  port: 8081
# **********************************************************************************************************************************
# Zipkin related stuff
# spring.sleuth.sampler.probability=1   for slueth
# sleuth skip pattern.  This is being enhance in version 2.1, should be able to remove then
# **********************************************************************************************************************************
spring.zipkin.discoveryClientEnabled: true
spring.zipkin.baseUrl: http://servicemesh-zipkin:9411
spring.sleuth.sampler.percentage: 1.0 
spring.sleuth.web.skipPattern: /api-docs.*|/autoconfig|/configprops|/dump|/health|/info|/metrics.*|/mappings|/trace|/swagger.*|/swagger-ui.*|.*\\.png|.*\\.css|.*\\.js|.*\\.html|/favicon.ico|/hystrix.stream|/application/.*|/actuator.*|/cloudfoundryapplication|/webjars
# **********************************************************************************************************************************
# THIS IS FOR THE /actuator/info ENDPOINT.  ADD ANY INFORMATION HERE TO BE PRESENTED.
# **********************************************************************************************************************************  
info:
  app:
    name: Member Info MicroService
    description: process Calling MTV API
management:
  endpoint:
    health:
      sensitive: false
      show-details: always
  info:
    git:
      mode: FULL
