//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 11:02:15 AM CDT 
//


package com.deanhealthplan.memberinfo.domain.api.networkidsearch;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.deanhealthplan.memberinfo.domain.api.networkidsearch package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MemberId_QNAME = new QName("", "MemberId");
    private final static QName _EffectiveDateStart_QNAME = new QName("", "EffectiveDateStart");
    private final static QName _EffectiveDateEnd_QNAME = new QName("", "EffectiveDateEnd");
    private final static QName _ContractId_QNAME = new QName("", "ContractId");
    private final static QName _NetworkId_QNAME = new QName("", "NetworkId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.deanhealthplan.memberinfo.domain.api.networkidsearch
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MemberInput }
     * 
     */
    public MemberInput createMemberInput() {
        return new MemberInput();
    }

    /**
     * Create an instance of {@link NetworkIdInput }
     * 
     */
    public NetworkIdInput createNetworkIdInput() {
        return new NetworkIdInput();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MemberId")
    public JAXBElement<String> createMemberId(String value) {
        return new JAXBElement<String>(_MemberId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EffectiveDateStart")
    public JAXBElement<String> createEffectiveDateStart(String value) {
        return new JAXBElement<String>(_EffectiveDateStart_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EffectiveDateEnd")
    public JAXBElement<String> createEffectiveDateEnd(String value) {
        return new JAXBElement<String>(_EffectiveDateEnd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ContractId")
    public JAXBElement<String> createContractId(String value) {
        return new JAXBElement<String>(_ContractId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NetworkId")
    public JAXBElement<String> createNetworkId(String value) {
        return new JAXBElement<String>(_NetworkId_QNAME, String.class, null, value);
    }

}
